language: node_js
node_js:
  - node
  - 6
  - 5
  - 4
  - 0.12
env:
before_script:
  - npm install -g gulp
  - gulp -v
script:
  #- npm run lint
  - yarn run build

  - rm -rf node_modules

  - cd examples
  - yarn
  #- npm test
  - gulp build
  - gulp build --type=production
